pyuic4 updateWnd.ui -o updateWnd.py
pyuic4 uploadWnd.ui -o uploadWnd.py
pyuic4 taskWnd.ui -o taskWnd.py
pyuic4 newsWnd.ui -o newsWnd.py
pyuic4 newsCurrentWnd.ui -o newsCurrentWnd.py
pyuic4 newsBaloon.ui -o newsBaloon.py
pyuic4 msgWnd.ui -o msgWnd.py
pyuic4 mainWnd.ui -o mainWnd.py
pyuic4 loginWnd.ui -o loginWnd.py
pyuic4 downloadWnd.ui -o downloadWnd.py
